### ISSUE TITLE
"Can't handle output buffer format" on Ubuntu 18.04

### ISSUE THREAD

**Issue by medakk** [raphlinus/synthesizer-io#10]
I get this error when I try to run:

```
format: Format { channels: 1, sample_rate: SampleRate(192000), data_type: I16 }
thread 'main' panicked at 'Can't handle output buffer format', src/main.rs:216:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panicking.rs:397
  12: synthesizer_io::run_cpal::{{closure}}
             at src/main.rs:216
  13: cpal::EventLoop::run::{{closure}}
             at /home/karthik/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/lib.rs:489
  14: cpal::cpal_impl::EventLoop::run_inner
             at /home/karthik/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/alsa/mod.rs:611
  15: cpal::cpal_impl::EventLoop::run
             at /home/karthik/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/alsa/mod.rs:408
  16: cpal::EventLoop::run
             at /home/karthik/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/lib.rs:489
  17: synthesizer_io::run_cpal
             at src/main.rs:197
  18: synthesizer_io::main
             at src/main.rs:168
  19: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: std::panicking::try
             at src/libstd/panicking.rs:281
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  27: main
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by AN1BRA** [comment]
I encountered the same problem in Ubuntu 20.04 :disappointed:

**Comment by ritschwumm** [comment]
192000 is a lot...
